import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

const metadata: Metadata = {
  title: "Hypen App",
  description: "Generated by Hypen app",
};

export const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  adjustFontFallback: false,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>{children}</body>
    </html>
  );
}
